#!/usr/bin/env node

// Sample proof of concept application for `node-complete`.
var complete = require('../../complete'); // get the `complete` module.

complete.installed(function(state) {
  if(state === false) {
    console.log('You have not installed this program. please run `' + complete.name + ' --install`.');
  }
});

//
// commands
// an array of commands that may be 
//
complete.list['apple', 'orange', 'pear', 'lemon', 'mango'];

//
// callback({string-data}, {array})
// gives you the opportunity to interact with the list before it is acted on.
// 
complete.callback = function(userInput, reducedList) {
  // do something if this is an orange.
};
