#!/usr/bin/env node

var complete = require('../../complete'); // get the `complete` module.

complete.installed(function(state) {
  if(state === false) {
    console.log('You have not installed this program. please run `' + complete.name + ' --install`.');
  }
});

complete.list = ['apple', 'orange', 'pear', 'lemon', 'mango'];

//
// callback({string-data}, {array})
// gives you the opportunity to interact with the list before it is acted on.
// 
complete.callback = function(userInput, reducedList) {
  // do something if this is an orange.
};

complete.init();
